# Verbosity and settings that you pretty much just always are going to want.
alias v="nvim"
alias sv="sudo nvim"
alias g="git"
alias l="lf"
alias sl="sudo lf"
alias f="fzf"
alias mkd="mkdir -pv"
alias grep="grep --color=auto"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkd="mkdir -pv"
alias rss="newsboat"
alias vz="v $HOME/.bashrc"
alias vza="v $DOTFILES/bashrc.d/20-aliases.sh"
alias vzf="v $DOTFILES/bashrc.d/50-functions.sh"
alias d="cd $DOTFILES"
alias Z="source $HOME/.bashrc"
# Show directory symbol (/) and hidden directories
alias ls='ls -p -a'
alias whitespace="sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'"